### ISSUE TITLE
Doesn't eneble after instal

### ISSUE THREAD

**Issue by cheteron** [Dangry98/PolyQuilt-for-Blender-4.0#12]
After install from extensions, show this error
![blender_L5gsjmB1bn](https://github.com/user-attachments/assets/d384343c-e583-4f68-b4c6-4094d3d99515)

Blender 4.2

**Comment by Dangry98** [comment]
Hi, please try restart Blender and reinstall, hopfully works then. I have been unable to repreduce this issue, so its a bit hard to fix unfortunately.

**Comment by cheteron** [comment]
Thanks, it worked after restart
