### ISSUE TITLE
gizmo Error

### ISSUE THREAD

**Issue by jeissonlazo** [Dangry98/PolyQuilt-for-Blender-4.0#9]
This error happens when you leave the PC still and come back when you are using polyquit,

After that you can't use the tool you have to save and restart blender
blender version 4.2

![Captura](https://github.com/user-attachments/assets/49953204-2523-4ae0-8be8-7aef04f828cd)

**Comment by Dangry98** [comment]
Hi @jeissonlazo, I let it run for a few hours in the backround, but everthing seems fine. Can you give a step by step to recreate the error and a .blend file if possible?

**Comment by jeissonlazo** [comment]
> Hi @jeissonlazo, thanks for the report.
> 
> I let it run for a few hours in the backround, but everthing seems fine so far. So I am unable to recreate the issue. Can you give a step by step to recreate the error and a .blend file if possible?

Let me make a more specific list of steps.

**Comment by jeissonlazo** [comment]
I reinstalled PolyQuilt and the error no longer appears.

**Comment by jeissonlazo** [comment]
The error disappears by reinstalling the plugin
